import React, { useState, useEffect, useRef } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { QRCodeSVG } from 'qrcode.react';
import jsPDF from 'jspdf';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext';
import AIChatbot from '../components/AIChatbot';

const API = 'http://localhost:5000';

const StatusBadge = ({ status }) => {
  const map = {
    confirmed: 'badge-blue', completed: 'badge-green', cancelled: 'badge-red',
    expired: 'badge-gray', no_show: 'badge-orange', pending: 'badge-yellow',
    scheduled: 'badge-blue', in_progress: 'badge-yellow', paid: 'badge-green',
  };
  return <span className={`badge ${map[status] || 'badge-gray'}`}>{status?.replace('_', ' ')}</span>;
};

export default function PatientDashboard() {
  const { user, updateUser } = useAuth();
  const [tab, setTab] = useState('overview');
  const [appointments, setAppointments] = useState([]);
  const [labTests, setLabTests] = useState([]);
  const [prescriptions, setPrescriptions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [chatOpen, setChatOpen] = useState(false);
  const [qrAppt, setQrAppt] = useState(null);
  const [profileForm, setProfileForm] = useState({
    name: user?.name || '', phone: user?.phone || '', address: user?.address || '',
    gender: user?.gender || '', bloodGroup: user?.bloodGroup || '',
  });
  const fileInputRef = useRef();

  useEffect(() => {
    Promise.all([
      axios.get('/api/appointments/my').then((r) => setAppointments(r.data)),
      axios.get('/api/lab-tests/my').then((r) => setLabTests(r.data)),
      axios.get(`/api/prescriptions/patient/${user._id}`).then((r) => setPrescriptions(r.data)),
    ]).finally(() => setLoading(false));
  }, []);

  const cancelAppointment = async (id) => {
    if (!confirm('Cancel this appointment?')) return;
    try {
      await axios.patch(`/api/appointments/${id}/cancel`);
      setAppointments((p) => p.map((a) => a._id === id ? { ...a, status: 'cancelled' } : a));
      toast.success('Appointment cancelled');
    } catch (err) { toast.error(err.response?.data?.message || 'Failed'); }
  };

  const handleProfilePic = async (e) => {
    const file = e.target.files[0]; if (!file) return;
    const fd = new FormData(); fd.append('profilePicture', file);
    try {
      const r = await axios.post('/api/users/upload-picture', fd, { headers: { 'Content-Type': 'multipart/form-data' } });
      updateUser({ profilePicture: r.data.profilePicture });
      toast.success('Profile picture updated!');
    } catch { toast.error('Upload failed'); }
  };

  const saveProfile = async () => {
    try {
      const r = await axios.patch('/api/users/profile', profileForm);
      updateUser(r.data);
      toast.success('Profile saved!');
    } catch { toast.error('Failed to save profile'); }
  };

  const downloadReport = (test) => {
    const doc = new jsPDF();
    doc.setFillColor(2, 6, 23); doc.rect(0, 0, 210, 297, 'F');
    doc.setTextColor(56, 189, 248); doc.setFontSize(22); doc.text('MediCare+', 20, 24);
    doc.setTextColor(255, 255, 255); doc.setFontSize(13); doc.text('Laboratory Test Report', 20, 34);
    doc.setDrawColor(14, 165, 233); doc.line(20, 38, 190, 38);
    doc.setFontSize(10); doc.setTextColor(150, 150, 150);
    doc.text(`Patient: ${user.name}`, 20, 50);
    doc.text(`Phone: ${user.phone || 'N/A'}`, 20, 58);
    doc.text(`Test: ${test.subCategory}`, 20, 66);
    doc.text(`Category: ${test.testCategory}`, 20, 74);
    doc.text(`Date: ${new Date(test.scheduledDate).toLocaleDateString('en-IN')} at ${test.scheduledTime}`, 20, 82);
    doc.text(`Token: ${test.tokenNumber}`, 20, 90);
    doc.text(`Amount: Rs. ${test.amount} (${test.paymentStatus})`, 20, 98);
    doc.setDrawColor(50, 50, 50); doc.line(20, 104, 190, 104);
    doc.setTextColor(255, 255, 255); doc.setFontSize(11); doc.text('Test Results', 20, 115);
    if (test.results?.notes) {
      doc.setFontSize(10); doc.setTextColor(200, 200, 200);
      const lines = doc.splitTextToSize(test.results.notes, 170);
      doc.text(lines, 20, 124);
    }
    if (test.results?.parameters?.length) {
      let y = test.results.notes ? 145 : 124;
      doc.setFontSize(10);
      test.results.parameters.forEach((p) => {
        const statusColor = p.status === 'high' ? [239, 68, 68] : p.status === 'low' ? [234, 179, 8] : [52, 211, 153];
        doc.setTextColor(...statusColor);
        doc.text(`${p.name}: ${p.value} ${p.unit || ''} (${p.normalRange || 'Normal'})`, 20, y);
        y += 8;
      });
    }
    doc.setFontSize(8); doc.setTextColor(80, 80, 80);
    doc.text('This report is generated by MediCare+ Hospital Management System.', 20, 275);
    doc.text(`Printed on: ${new Date().toLocaleDateString()}`, 20, 282);
    doc.save(`lab-report-${test.tokenNumber}-${user.name.replace(/ /g, '_')}.pdf`);
    toast.success('Report downloaded!');
  };

  const upcoming = appointments.filter((a) => a.status === 'confirmed' && new Date(a.appointmentDate) >= new Date());

  const TABS = [
    { id: 'overview', label: ' Overview' },
    { id: 'appointments', label: ' Appointments' },
    { id: 'labtests', label: ' Lab Tests' },
    { id: 'prescriptions', label: ' Prescriptions' },
    { id: 'profile', label: ' Profile' },
  ];

  if (loading) return (
    <div className="page flex items-center justify-center min-h-[60vh]">
      <div className="text-center"><div className="spinner spinner-lg mx-auto mb-4"></div><p className="text-slate-400">Loading your health dashboard...</p></div>
    </div>
  );

  return (
    <div className="page">
      {/* Profile header */}
      <div className="flex flex-col sm:flex-row items-start sm:items-center gap-5 mb-8">
        <div className="relative flex-shrink-0">
          <div
            className="w-20 h-20 rounded-2xl overflow-hidden"
            style={{ background: 'linear-gradient(135deg, #0ea5e9, #10b981)' }}
          >
            {user?.profilePicture
              ? <img src={`${API}${user.profilePicture}`} alt="" className="w-full h-full object-cover" />
              : <div className="w-full h-full flex items-center justify-center text-white text-3xl font-bold">{user?.name?.[0]}</div>}
          </div>
          <button
            onClick={() => fileInputRef.current?.click()}
            className="absolute -bottom-1.5 -right-1.5 w-8 h-8 rounded-lg flex items-center justify-center"
            style={{ background: '#0ea5e9', border: '2px solid #020617' }}
            title="Change photo"
          >
            <svg className="w-3.5 h-3.5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 9a2 2 0 012-2h.93a2 2 0 001.664-.89l.812-1.22A2 2 0 0110.07 4h3.86a2 2 0 011.664.89l.812 1.22A2 2 0 0018.07 7H19a2 2 0 012 2v9a2 2 0 01-2 2H5a2 2 0 01-2-2V9z" />
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 13a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
          </button>
          <input ref={fileInputRef} type="file" className="hidden" accept="image/jpeg,image/png,image/webp" onChange={handleProfilePic} />
        </div>
        <div className="flex-1">
          <h1 className="text-2xl font-display font-bold text-white">
            Good {new Date().getHours() < 12 ? 'Morning' : new Date().getHours() < 17 ? 'Afternoon' : 'Evening'}, {user?.name?.split(' ')[0]}! 👋
          </h1>
          <p className="text-slate-400 text-sm mt-0.5">{user?.email} • Patient ID #{user?._id?.slice(-8).toUpperCase()}</p>
          <div className="flex flex-wrap gap-2 mt-2">
            {user?.gender && <span className="badge badge-blue">{user.gender}</span>}
            {user?.bloodGroup && <span className="badge badge-red">Blood: {user.bloodGroup}</span>}
            {user?.address && <span className="badge badge-gray">📍 {user.address}</span>}
          </div>
        </div>
        <div className="flex gap-3 flex-shrink-0">
          <Link to="/book-appointment" className="btn btn-primary btn-sm">Appointment</Link>
          <Link to="/book-lab-test" className="btn btn-success btn-sm"> Lab Test</Link>
        </div>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-8">
        {[
          { label: 'Upcoming', value: upcoming.length, icon: '', color: '#0ea5e9' },
          { label: 'Lab Tests', value: labTests.length, icon: '', color: '#10b981' },
          { label: 'Prescriptions', value: prescriptions.length, icon: '', color: '#8b5cf6' },
          { label: 'Total Paid', value: `₹${labTests.filter((t) => t.paymentStatus === 'paid').reduce((s, t) => s + t.amount, 0)}`, icon: '💰', color: '#f59e0b' },
        ].map((s, i) => (
          <div key={i} className="stat-card">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xl">{s.icon}</span>
              <div className="w-2 h-2 rounded-full" style={{ background: s.color }}></div>
            </div>
            <p className="text-2xl font-bold text-white">{s.value}</p>
            <p className="text-slate-500 text-xs mt-0.5">{s.label}</p>
          </div>
        ))}
      </div>

      {/* Tabs */}
      <div className="tab-bar mb-6">
        {TABS.map((t) => (
          <button key={t.id} onClick={() => setTab(t.id)} className={`tab-btn ${tab === t.id ? 'active' : ''}`}>
            {t.label}
          </button>
        ))}
      </div>

      {/* ── Overview ── */}
      {tab === 'overview' && (
        <div className="grid md:grid-cols-2 gap-6">
          <div className="glass-card p-5">
            <div className="section-header">
              <h3 className="section-title"> Recent Appointments</h3>
              <Link to="#" onClick={() => setTab('appointments')} className="text-xs text-sky-400 hover:text-sky-300">View all →</Link>
            </div>
            <div className="space-y-3">
              {appointments.slice(0, 4).map((a) => (
                <div key={a._id} className="list-row">
                  <div className="avatar w-10 h-10 text-sm">{a.doctor?.name?.[0]}</div>
                  <div className="flex-1 min-w-0">
                    <p className="text-white text-sm font-semibold truncate">Dr. {a.doctor?.name}</p>
                    <p className="text-slate-500 text-xs">{new Date(a.appointmentDate).toLocaleDateString('en-IN')} • {a.appointmentTime}</p>
                  </div>
                  <StatusBadge status={a.status} />
                </div>
              ))}
              {appointments.length === 0 && <p className="text-slate-500 text-sm text-center py-8">No appointments yet. <Link to="/book-appointment" className="text-sky-400">Book now →</Link></p>}
            </div>
          </div>

          <div className="glass-card p-5">
            <div className="section-header">
              <h3 className="section-title"> Recent Lab Tests</h3>
              <Link to="#" onClick={() => setTab('labtests')} className="text-xs text-emerald-400 hover:text-emerald-300">View all →</Link>
            </div>
            <div className="space-y-3">
              {labTests.slice(0, 4).map((t) => (
                <div key={t._id} className="list-row">
                  <div className="w-10 h-10 rounded-xl flex items-center justify-center text-lg flex-shrink-0" style={{ background: 'rgba(16,185,129,0.1)' }}>🔬</div>
                  <div className="flex-1 min-w-0">
                    <p className="text-white text-sm font-semibold truncate">{t.subCategory}</p>
                    <p className="text-slate-500 text-xs">{new Date(t.scheduledDate).toLocaleDateString('en-IN')} • ₹{t.amount}</p>
                  </div>
                  <StatusBadge status={t.status} />
                </div>
              ))}
              {labTests.length === 0 && <p className="text-slate-500 text-sm text-center py-8">No lab tests yet. <Link to="/book-lab-test" className="text-emerald-400">Book now →</Link></p>}
            </div>
          </div>
        </div>
      )}

      {/* ── Appointments ── */}
      {tab === 'appointments' && (
        <div className="space-y-3">
          {appointments.length === 0 ? (
            <div className="glass-card p-16 text-center">
              <p className="text-5xl mb-4"></p>
              <p className="text-white font-bold text-lg mb-2">No appointments yet</p>
              <p className="text-slate-400 text-sm mb-6">Book your first appointment with a specialist</p>
              <Link to="/book-appointment" className="btn btn-primary">Book Appointment</Link>
            </div>
          ) : appointments.map((a) => (
            <div key={a._id} className="glass-card p-5 flex flex-col sm:flex-row gap-4">
              <div className="flex items-center gap-4 flex-1 min-w-0">
                <div className="avatar w-14 h-14 text-xl flex-shrink-0">{a.doctor?.name?.[0]}</div>
                <div className="flex-1 min-w-0">
                  <p className="text-white font-bold">Dr. {a.doctor?.name}</p>
                  <p className="text-sky-400 text-sm">{a.doctor?.specialization}</p>
                  <p className="text-slate-400 text-xs mt-1">
                    {new Date(a.appointmentDate).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} at {a.appointmentTime}
                  </p>
                  {a.symptoms && <p className="text-slate-500 text-xs mt-1 truncate">Reason: {a.symptoms}</p>}
                </div>
              </div>
              <div className="flex items-center gap-3 flex-wrap sm:flex-shrink-0">
                <div className="text-center">
                  <p className="text-xs text-slate-500">Token</p>
                  <p className="text-sky-400 font-bold text-base">#{ a.tokenNumber}</p>
                </div>
                <StatusBadge status={a.status} />
                {a.status === 'confirmed' && (
                  <>
                    <button
                      onClick={() => setQrAppt(a)}
                      className="btn btn-ghost btn-sm"
                    >
                      📱 QR Code
                    </button>
                    <button
                      onClick={() => cancelAppointment(a._id)}
                      className="btn btn-sm"
                      style={{ background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)', color: '#f87171' }}
                    >
                      Cancel
                    </button>
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ── Lab Tests ── */}
      {tab === 'labtests' && (
        <div className="space-y-3">
          {labTests.length === 0 ? (
            <div className="glass-card p-16 text-center">
              <p className="text-5xl mb-4">🧪</p>
              <p className="text-white font-bold text-lg mb-2">No lab tests booked</p>
              <Link to="/book-lab-test" className="btn btn-success mt-4 inline-block">Book Lab Test</Link>
            </div>
          ) : labTests.map((t) => (
            <div key={t._id} className="glass-card p-5 flex flex-col sm:flex-row gap-4">
              <div className="flex items-center gap-4 flex-1 min-w-0">
                <div className="w-14 h-14 rounded-xl flex items-center justify-center text-2xl flex-shrink-0" style={{ background: 'rgba(16,185,129,0.08)', border: '1px solid rgba(16,185,129,0.15)' }}>🔬</div>
                <div className="flex-1 min-w-0">
                  <p className="text-white font-bold">{t.subCategory}</p>
                  <p className="text-emerald-400 text-sm">{t.testCategory}</p>
                  <p className="text-slate-400 text-xs mt-1">
                    {new Date(t.scheduledDate).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })} at {t.scheduledTime}
                  </p>
                  <p className="text-slate-500 text-xs">Amount: ₹{t.amount} • Token: {t.tokenNumber}</p>
                </div>
              </div>
              <div className="flex items-center gap-3 flex-wrap sm:flex-shrink-0">
                <StatusBadge status={t.paymentStatus} />
                <StatusBadge status={t.status} />
                {t.status === 'completed' && t.results && (
                  <button onClick={() => downloadReport(t)} className="btn btn-sm" style={{ background: 'rgba(14,165,233,0.08)', border: '1px solid rgba(14,165,233,0.2)', color: '#38bdf8' }}>
                    ↓ Report
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* ── Prescriptions ── */}
      {tab === 'prescriptions' && (
        <div className="space-y-4">
          {prescriptions.length === 0 ? (
            <div className="glass-card p-16 text-center">
              <p className="text-5xl mb-4">💊</p>
              <p className="text-white font-bold text-lg">No prescriptions yet</p>
              <p className="text-slate-400 text-sm mt-2">Prescriptions will appear here after a doctor's consultation</p>
            </div>
          ) : prescriptions.map((p) => (
            <div key={p._id} className="glass-card p-6">
              <div className="flex items-start justify-between mb-4 flex-wrap gap-3">
                <div className="flex items-center gap-3">
                  <div className="avatar w-12 h-12 text-sm">{p.doctor?.name?.[0]}</div>
                  <div>
                    <p className="text-white font-bold">Dr. {p.doctor?.name}</p>
                    <p className="text-sky-400 text-sm">{p.doctor?.specialization}</p>
                    <p className="text-slate-500 text-xs">{new Date(p.createdAt).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
                  </div>
                </div>
                {p.nextCheckupDate && (
                  <div className="text-right">
                    <p className="text-xs text-slate-500">Next Checkup</p>
                    <p className="text-emerald-400 font-bold text-sm">{new Date(p.nextCheckupDate).toLocaleDateString('en-IN')}</p>
                  </div>
                )}
              </div>

              <div className="p-3 rounded-xl mb-4" style={{ background: 'rgba(14,165,233,0.05)', border: '1px solid rgba(14,165,233,0.1)' }}>
                <p className="text-xs text-slate-500 font-semibold mb-1">DIAGNOSIS</p>
                <p className="text-white text-sm">{p.diagnosis}</p>
              </div>

              {p.medicines?.length > 0 && (
                <div className="mb-4">
                  <p className="text-xs text-slate-500 font-semibold mb-2">MEDICINES ({p.medicines.length})</p>
                  <div className="grid sm:grid-cols-2 gap-2">
                    {p.medicines.map((m, i) => (
                      <div key={i} className="p-3 rounded-xl" style={{ background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.06)' }}>
                        <p className="text-white text-sm font-semibold">💊 {m.name}</p>
                        <p className="text-slate-400 text-xs mt-0.5">{m.dosage} • {m.frequency} • {m.duration}</p>
                        {m.instructions && <p className="text-slate-500 text-xs italic mt-0.5">{m.instructions}</p>}
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {p.injections?.length > 0 && (
                <div className="mb-4">
                  <p className="text-xs text-slate-500 font-semibold mb-2">INJECTIONS ({p.injections.length})</p>
                  <div className="flex flex-wrap gap-2">
                    {p.injections.map((inj, i) => (
                      <span key={i} className="badge badge-purple">💉 {inj.name} {inj.dosage}</span>
                    ))}
                  </div>
                </div>
              )}

              {p.notes && (
                <div className="p-3 rounded-xl" style={{ background: 'rgba(255,255,255,0.02)' }}>
                  <p className="text-xs text-slate-500 font-semibold mb-1">NOTES</p>
                  <p className="text-slate-300 text-sm">{p.notes}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* ── Profile ── */}
      {tab === 'profile' && (
        <div className="max-w-xl">
          <div className="glass-card p-6">
            <h3 className="section-title mb-5">Edit Profile</h3>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="sm:col-span-2 form-group">
                <label className="form-label">Full Name</label>
                <input className="input" value={profileForm.name} onChange={(e) => setProfileForm((p) => ({ ...p, name: e.target.value }))} />
              </div>
              <div className="form-group">
                <label className="form-label">Phone</label>
                <input className="input" value={profileForm.phone} onChange={(e) => setProfileForm((p) => ({ ...p, phone: e.target.value }))} />
              </div>
              <div className="form-group">
                <label className="form-label">Address / City</label>
                <input className="input" value={profileForm.address} onChange={(e) => setProfileForm((p) => ({ ...p, address: e.target.value }))} />
              </div>
              <div className="form-group">
                <label className="form-label">Gender</label>
                <select className="input" value={profileForm.gender} onChange={(e) => setProfileForm((p) => ({ ...p, gender: e.target.value }))} style={{ background: 'rgba(255,255,255,0.04)' }}>
                  <option value="">Select</option>
                  <option value="male">Male</option>
                  <option value="female">Female</option>
                  <option value="other">Other</option>
                </select>
              </div>
              <div className="form-group">
                <label className="form-label">Blood Group</label>
                <select className="input" value={profileForm.bloodGroup} onChange={(e) => setProfileForm((p) => ({ ...p, bloodGroup: e.target.value }))} style={{ background: 'rgba(255,255,255,0.04)' }}>
                  <option value="">Select</option>
                  {['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map((b) => <option key={b} value={b}>{b}</option>)}
                </select>
              </div>
              <div className="sm:col-span-2">
                <button onClick={saveProfile} className="btn btn-primary w-full py-3">Save Changes</button>
              </div>
            </div>
          </div>

          <div className="glass-card p-6 mt-4">
            <h3 className="section-title mb-4">Account Info</h3>
            <div className="space-y-3 text-sm">
              {[['Email', user?.email], ['Role', 'Patient'], ['Member Since', new Date(user?.createdAt || Date.now()).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })]].map(([k, v]) => (
                <div key={k} className="flex justify-between py-2" style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}>
                  <span className="text-slate-500">{k}</span>
                  <span className="text-white">{v}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* QR Modal */}
      {qrAppt && (
        <div className="modal-overlay" onClick={() => setQrAppt(null)}>
          <div className="modal-box max-w-sm" onClick={(e) => e.stopPropagation()}>
            <div className="flex justify-between items-center mb-5">
              <h3 className="text-white font-bold text-lg">Appointment QR Code</h3>
              <button onClick={() => setQrAppt(null)} className="text-slate-400 hover:text-white">✕</button>
            </div>
            <div className="flex justify-center mb-5 p-4 rounded-xl bg-white">
              {qrAppt && qrAppt.tokenNumber ? (
                <QRCodeSVG
                  value={qrAppt.qrCode || JSON.stringify({ 
                    token: qrAppt.tokenNumber || '', 
                    patient: user?.name || 'Patient', 
                    doctor: qrAppt.doctor?.name || 'Doctor', 
                    date: qrAppt.appointmentDate || '', 
                    time: qrAppt.appointmentTime || ''
                  })}
                  size={200}
                  level="M"
                  includeMargin={true}
                  bgColor="#ffffff"
                  fgColor="#000000"
                />
              ) : (
                <div className="text-slate-500 text-sm">No appointment data available</div>
              )}
            </div>
            <div className="space-y-2.5">
              {[
                ['Token Number', `#${qrAppt.tokenNumber}`],
                ['Doctor', `Dr. ${qrAppt.doctor?.name}`],
                ['Specialization', qrAppt.doctor?.specialization],
                ['Date', new Date(qrAppt.appointmentDate).toLocaleDateString('en-IN', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })],
                ['Time', qrAppt.appointmentTime],
              ].map(([k, v]) => (
                <div key={k} className="flex justify-between text-sm">
                  <span className="text-slate-500">{k}</span>
                  <span className={k === 'Token Number' ? 'text-sky-400 font-bold text-base' : 'text-white font-medium'}>{v}</span>
                </div>
              ))}
            </div>
            <p className="text-slate-500 text-xs text-center mt-5 leading-relaxed">
              📱 Show this QR code at reception upon arrival.<br />
              Must arrive within <strong className="text-yellow-400">30 minutes</strong> of appointment time.
            </p>
          </div>
        </div>
      )}

      {/* AI Chatbot button */}
      {!chatOpen && (
        <button
          onClick={() => setChatOpen(true)}
          className="fixed bottom-6 right-6 w-14 h-14 rounded-full flex items-center justify-center text-2xl z-40 transition-all hover:scale-110 shadow-2xl"
          style={{ background: 'linear-gradient(135deg, #0ea5e9, #10b981)', boxShadow: '0 8px 32px rgba(14,165,233,0.4)' }}
          title="AI Health Assistant"
        >
          🤖
        </button>
      )}
      {chatOpen && <AIChatbot onClose={() => setChatOpen(false)} />}
    </div>
  );
}
